// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	proxy "github.com/nusiss-capstone-project/asset-mservice/server/proxy"
	mock "github.com/stretchr/testify/mock"
)

// PaymentProxy is an autogenerated mock type for the PaymentProxy type
type PaymentProxy struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, req
func (_m *PaymentProxy) CreatePayment(ctx context.Context, req proxy.CreatePaymentRequest) (*proxy.CreatePaymentResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *proxy.CreatePaymentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.CreatePaymentRequest) (*proxy.CreatePaymentResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.CreatePaymentRequest) *proxy.CreatePaymentResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.CreatePaymentResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.CreatePaymentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentProxy creates a new instance of PaymentProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentProxy {
	mock := &PaymentProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
