// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	identitypb "github.com/nusiss-capstone-project/identity-mservice/common/identitypb"
	mock "github.com/stretchr/testify/mock"
)

type UserProxy struct {
	mock.Mock
}

func (_m *UserProxy) GetUserProfile(ctx context.Context, userID int64) (*identitypb.GetUserProfileResponse, error) {
	ret := _m.Called(ctx, userID)
	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}
	var r0 *identitypb.GetUserProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*identitypb.GetUserProfileResponse, error)); ok {
		return rf(ctx, userID)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*identitypb.GetUserProfileResponse)
	}
	r1 = ret.Error(1)
	return r0, r1
}
