// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/asset-mservice/server/repository/model"
)

// AccountLedgerDao is an autogenerated mock type for the AccountLedgerDao type
type AccountLedgerDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, ledger
func (_m *AccountLedgerDao) Create(ctx context.Context, tx *gorm.DB, ledger *model.AccountLedger) error {
	ret := _m.Called(ctx, tx, ledger)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.AccountLedger) error); ok {
		r0 = rf(ctx, tx, ledger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountLedgerDao creates a new instance of AccountLedgerDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountLedgerDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountLedgerDao {
	mock := &AccountLedgerDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
