// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dao "github.com/nusiss-capstone-project/asset-mservice/server/repository/dao"
	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/asset-mservice/server/repository/model"
)

// AssetDao is an autogenerated mock type for the AssetDao type
type AssetDao struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AssetDao) GetByID(ctx context.Context, id int64) (*model.Asset, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Asset, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Asset); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ctx, ids
func (_m *AssetDao) GetByIDs(ctx context.Context, ids []int64) ([]*model.Asset, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*model.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]*model.Asset, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []*model.Asset); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *AssetDao) List(ctx context.Context, filter dao.AssetListFilter) ([]*model.Asset, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.AssetListFilter) ([]*model.Asset, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.AssetListFilter) []*model.Asset); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.AssetListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAssetDao creates a new instance of AssetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetDao {
	mock := &AssetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
