// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dao "github.com/nusiss-capstone-project/asset-mservice/server/repository/dao"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/asset-mservice/server/repository/model"
)

// AssetOrderDao is an autogenerated mock type for the AssetOrderDao type
type AssetOrderDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, order
func (_m *AssetOrderDao) Create(ctx context.Context, tx *gorm.DB, order *model.AssetOrder) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.AssetOrder) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AssetOrderDao) GetByID(ctx context.Context, id int64) (*model.AssetOrder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.AssetOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.AssetOrder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.AssetOrder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AssetOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdempotencyKey provides a mock function with given fields: ctx, userID, key
func (_m *AssetOrderDao) GetByIdempotencyKey(ctx context.Context, userID int64, key string) (*model.AssetOrder, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *model.AssetOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*model.AssetOrder, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *model.AssetOrder); ok {
		r0 = rf(ctx, userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AssetOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByOrderNo provides a mock function with given fields: ctx, orderNo
func (_m *AssetOrderDao) GetByOrderNo(ctx context.Context, orderNo string) (*model.AssetOrder, error) {
	ret := _m.Called(ctx, orderNo)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderNo")
	}

	var r0 *model.AssetOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AssetOrder, error)); ok {
		return rf(ctx, orderNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AssetOrder); ok {
		r0 = rf(ctx, orderNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AssetOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByCursor provides a mock function with given fields: ctx, filter
func (_m *AssetOrderDao) ListByCursor(ctx context.Context, filter dao.AssetOrderListFilter) ([]*model.AssetOrder, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListByCursor")
	}

	var r0 []*model.AssetOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.AssetOrderListFilter) ([]*model.AssetOrder, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.AssetOrderListFilter) []*model.AssetOrder); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AssetOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.AssetOrderListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePaymentResult provides a mock function with given fields: ctx, tx, id, paymentID, fromStatus, toStatus
func (_m *AssetOrderDao) UpdatePaymentResult(ctx context.Context, tx *gorm.DB, id int64, paymentID string, fromStatus string, toStatus string) (int64, error) {
	ret := _m.Called(ctx, tx, id, paymentID, fromStatus, toStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentResult")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string, string, string) (int64, error)); ok {
		return rf(ctx, tx, id, paymentID, fromStatus, toStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string, string, string) int64); ok {
		r0 = rf(ctx, tx, id, paymentID, fromStatus, toStatus)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64, string, string, string) error); ok {
		r1 = rf(ctx, tx, id, paymentID, fromStatus, toStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAssetOrderDao creates a new instance of AssetOrderDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssetOrderDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetOrderDao {
	mock := &AssetOrderDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
