// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"
	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/asset-mservice/server/repository/model"
)

type FiatTransactionDao struct {
	mock.Mock
}

func (_m *FiatTransactionDao) Create(ctx context.Context, tx *gorm.DB, txn *model.FiatTransaction) error {
	ret := _m.Called(ctx, tx, txn)
	return ret.Error(0)
}

func (_m *FiatTransactionDao) GetByID(ctx context.Context, id int64) (*model.FiatTransaction, error) {
	ret := _m.Called(ctx, id)
	var r0 *model.FiatTransaction
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.FiatTransaction)
	}
	return r0, ret.Error(1)
}

func (_m *FiatTransactionDao) GetByIdempotentKey(ctx context.Context, userID int64, key string) (*model.FiatTransaction, error) {
	ret := _m.Called(ctx, userID, key)
	var r0 *model.FiatTransaction
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.FiatTransaction)
	}
	return r0, ret.Error(1)
}

func (_m *FiatTransactionDao) UpdatePaymentResult(ctx context.Context, tx *gorm.DB, id int64, paymentID, fromStatus, toStatus, failureReason string) (int64, error) {
	ret := _m.Called(ctx, tx, id, paymentID, fromStatus, toStatus, failureReason)
	return ret.Get(0).(int64), ret.Error(1)
}

func (_m *FiatTransactionDao) UpdateAccountID(ctx context.Context, tx *gorm.DB, id, accountID int64) error {
	ret := _m.Called(ctx, tx, id, accountID)
	return ret.Error(0)
}
