// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	gorm "gorm.io/gorm"
	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/asset-mservice/server/repository/model"
)

type UserFiatAccountDao struct {
	mock.Mock
}

func (_m *UserFiatAccountDao) ListByUser(ctx context.Context, userID int64) ([]*model.UserFiatAccount, error) {
	ret := _m.Called(ctx, userID)
	var r0 []*model.UserFiatAccount
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*model.UserFiatAccount)
	}
	return r0, ret.Error(1)
}

func (_m *UserFiatAccountDao) GetByUserAndCurrency(ctx context.Context, userID int64, currency string) (*model.UserFiatAccount, error) {
	ret := _m.Called(ctx, userID, currency)
	var r0 *model.UserFiatAccount
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*model.UserFiatAccount)
	}
	return r0, ret.Error(1)
}

func (_m *UserFiatAccountDao) UpsertAddBalance(ctx context.Context, tx *gorm.DB, userID int64, currency string, amount decimal.Decimal) (decimal.Decimal, int64, error) {
	ret := _m.Called(ctx, tx, userID, currency, amount)
	var r0 decimal.Decimal
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(decimal.Decimal)
	}
	return r0, ret.Get(1).(int64), ret.Error(2)
}
