// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/asset-mservice/server/repository/model"
)

// UserAssetHoldingDao is an autogenerated mock type for the UserAssetHoldingDao type
type UserAssetHoldingDao struct {
	mock.Mock
}

// GetByUserAndAsset provides a mock function with given fields: ctx, userID, assetID
func (_m *UserAssetHoldingDao) GetByUserAndAsset(ctx context.Context, userID int64, assetID int64) (*model.UserAssetHolding, error) {
	ret := _m.Called(ctx, userID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndAsset")
	}

	var r0 *model.UserAssetHolding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*model.UserAssetHolding, error)); ok {
		return rf(ctx, userID, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *model.UserAssetHolding); ok {
		r0 = rf(ctx, userID, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAssetHolding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUser provides a mock function with given fields: ctx, userID, assetID
func (_m *UserAssetHoldingDao) ListByUser(ctx context.Context, userID int64, assetID int64) ([]*model.UserAssetHolding, error) {
	ret := _m.Called(ctx, userID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*model.UserAssetHolding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]*model.UserAssetHolding, error)); ok {
		return rf(ctx, userID, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []*model.UserAssetHolding); ok {
		r0 = rf(ctx, userID, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserAssetHolding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertAddQuantity provides a mock function with given fields: ctx, tx, userID, assetID, quantity
func (_m *UserAssetHoldingDao) UpsertAddQuantity(ctx context.Context, tx *gorm.DB, userID int64, assetID int64, quantity decimal.Decimal) (decimal.Decimal, error) {
	ret := _m.Called(ctx, tx, userID, assetID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAddQuantity")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, int64, decimal.Decimal) (decimal.Decimal, error)); ok {
		return rf(ctx, tx, userID, assetID, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, int64, decimal.Decimal) decimal.Decimal); ok {
		r0 = rf(ctx, tx, userID, assetID, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(decimal.Decimal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64, int64, decimal.Decimal) error); ok {
		r1 = rf(ctx, tx, userID, assetID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserAssetHoldingDao creates a new instance of UserAssetHoldingDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserAssetHoldingDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAssetHoldingDao {
	mock := &UserAssetHoldingDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
