// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	producer "github.com/nusiss-capstone-project/asset-mservice/server/kafka/producer"
	mock "github.com/stretchr/testify/mock"
)

type DepositPaymentResultProducer struct {
	mock.Mock
}

func (_m *DepositPaymentResultProducer) PublishDepositPaymentResult(ctx context.Context, event producer.DepositPaymentResultEvent) error {
	ret := _m.Called(ctx, event)
	return ret.Error(0)
}
