// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	producer "github.com/nusiss-capstone-project/asset-mservice/server/kafka/producer"
	mock "github.com/stretchr/testify/mock"
)

// OrderPaymentResultProducer is an autogenerated mock type for the OrderPaymentResultProducer type
type OrderPaymentResultProducer struct {
	mock.Mock
}

// PublishOrderPaymentResult provides a mock function with given fields: ctx, event
func (_m *OrderPaymentResultProducer) PublishOrderPaymentResult(ctx context.Context, event producer.OrderPaymentResultEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderPaymentResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, producer.OrderPaymentResultEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderPaymentResultProducer creates a new instance of OrderPaymentResultProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaymentResultProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaymentResultProducer {
	mock := &OrderPaymentResultProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
